WITH RECURSIVE TEMP AS (
    SELECT
        E.ID,
        1 AS GENERATION
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID IS NULL

    UNION ALL

    SELECT 
        E.ID,
        T.GENERATION + 1 AS GENERATION
    FROM TEMP T
    JOIN ECOLI_DATA E ON E.PARENT_ID = T.ID
)

SELECT 
    COUNT(*) AS COUNT, T.GENERATION
FROM temp t
LEFT JOIN ECOLI_DATA c ON c.parent_id = t.id
WHERE c.id IS NULL
GROUP BY GENERATION;

# SELECT COUNT(*) AS COUNT, GENERATION
# FROM TEMP
# GROUP BY GENERATION;
